<ViewTripsAdminScreen>:
    name: "view_trips_admin"

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        Label:
            text: "Pantalla de viajes - Administrador"
            font_size: 24
            size_hint_y: None
            height: self.texture_size[1]

        Button:
            text: "Volver"
            size_hint_y: None
            height: 50
            on_release:
                app.root.current = "dashboard_admin"
